[default]
src = 'contracts'
out = 'out'
test = 'sol-tests'
libs = ['lib']
gas_reports = ['Proxy', 'Party', 'PartyGovernance', 'ProposalExecutionEngine']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
