name: Tests

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

env:
  FORK_URL: ${{ secrets.FORK_URL }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn install
      - name: Build ts
        run: yarn build:ts
      - name: "Install Foundry"
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        run: forge install
      - name: "Run Foundry tests"
        run: forge test -vvv --no-match-contract "ForkedTest" --ffi
  test-forked:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install yarn dependencies
        run: yarn install
      - name: Build ts
        run: yarn build:ts
      - name: "Install Foundry"
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        run: forge install
      - name: "Run Foundry tests"
        run: forge test -vvv --fork-url $FORK_URL --match-contract "ForkedTest" --ffi
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn install
      - name: "Install Foundry"
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        run: forge install
      - name: Run Foundry Coverage
        run: yarn coverage
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn install
      - name: Run Linter
        run: yarn lint:check
  contracts-deployable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn install
      - name: Build ts
        run: yarn build:ts
      - name: "Install Foundry"
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        run: forge install
      - name: Check contract deployable mainnet
        run: "node js/contracts-deployable.js --via-ir --optimize --optimizer-runs 100"
      - name: Check contracts deployable base
        run: "node js/contracts-deployable.js --via-ir --optimize --optimizer-runs 0 --evm-version paris"
