name: Pull Request

on: pull_request

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@marcusmolchany" # we can make this whoever
      - run: forge test -vvv
      - run: yarn
      - run: yarn test:ts
      # - run: forge snapshot
