name: Pull Request

on: pull_request

env:
  # For TS forked tests to run too
  FORK_URL: ${{ secrets.FORK_URL }}

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v3
      - run: npm install --dev
      - run: forge test -vvv --fork-url ${{ secrets.FORK_URL }} --etherscan-api-key ${{ secrets.ETHERSCAN_API_KEY }}
      - run: npm run test:ts
      # - run: forge snapshot
